# Generated by Django 3.1.4 on 2020-12-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201226_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/shanks007/image/upload/v1609004177/media/default_ss4wa6.jpg', upload_to='profile/'),
        ),
    ]
